spring:
  application:
    name: promox-flashsale-service
  datasource:
    url: jdbc:postgresql://localhost:5432/promox_db
    username: promox
    password: promox123
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 9003

logging:
  level:
    com.promox.flashsale: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
