spring:
  application:
    name: promox-coupon-service
  datasource:
    url: jdbc:postgresql://localhost:5432/promox_db
    username: promox
    password: promox123
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

server:
  port: 9004

logging:
  level:
    com.promox.coupon: DEBUG
